### ISSUE TITLE
Would you consider re-licensing this repository?

### ISSUE THREAD

**Issue by arfon** [psicomante/CLIPS-sublime#2]
Hello there, we'd love to use this library to syntax-highlight files on GitHub but in order to do so we need this library to have a more permissive license.

If you don't have any particular reason for choosing GPL would you be willing to consider switching this to a more permissive license such as MIT, BSD or Apache 2?

Many thanks
Arfon (GitHub Staff)

**Comment by pchaigno** [comment]
@psicomante Did you get a chance to look into this?

**Comment by psicomante** [comment]
Hello @arfon and @pchaigno ! Sorry for the delay! I'm very happy that you guys at Github will use this simple syntax-highlighter.

Sure i will change the licence to MIT now.

Thanks for the issue.

**Comment by pchaigno** [comment]
Thanks @psicomante!
